### Get all users
GET http://localhost:5000/users

### Register a vendor
POST http://localhost:5000/auth/register
Content-Type: application/json

{
  "businessName": "TechSupplies Pvt Ltd",
  "businessEmail": "sales@techsupplies.com",
  "businessPhone": "9876543210",
  "businessAddress": "Bangalore, India",
  "phone": "9876543210",
  "designation": "Manager",
  "department": "IT",

  "email": "vendor@example.com",
  "password": "password123",
  "name": "vendor name",
  "role": "vendor"
}


### Register a approver
POST http://localhost:5000/auth/register
Content-Type: application/json

{
  "phone": "9876543210",
  "designation": "Manager",
  "department": "IT",

  "email": "approver@example.com",
  "password": "password123",
  "name": "approver name",
  "role": "approver"
}

### Register a buyer
POST http://localhost:5000/auth/register
Content-Type: application/json

{
  "email": "buyer@example.com",
  "password": "password123",
  "name": "buyer name",
  "role": "buyer",
  "phone": "9876543210"
}

### Register a admin
POST http://localhost:5000/auth/register
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "password123",
  "name": "admin name",
  "role": "admin",
  "phone": "9876543210"
}


### Login vendor
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "email": "vendor@example.com",
  "password": "password123"
}

### Login approver
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "email": "approver@example.com",
  "password": "password123"
}


### Login buyer
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "email": "buyer@example.com",
  "password": "password123"
}

### Login admin
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "password123"
}


### Manually set the access token here after login
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmZTE4NjcwNS00ZTUyLTRjOGMtYmNlNC00YTljYWVlZTlhMDAiLCJpYXQiOjE3NjIwOTE3NTQsImV4cCI6MTc2MjA5MjY1NH0.HXiTrRWT_3YPd-EghW-YcDKwkP70vvfaz85-yXwaZ4Y

@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTJjZTYzYy1lZDk5LTQxMzUtYWFiMC05ZGU1YTkyODBlZWIiLCJpYXQiOjE3NjIwODI4NzgsImV4cCI6MTc2MjY4NzY3OH0.1jTCI-4Nu2GlzZ93xgldWff9Gl8DmvClvcLL0vMqX8M

### Refresh Token
POST http://localhost:5000/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

###  Fetch all categories with parent and children
GET http://localhost:5000/product/getAllCategories
Content-Type: application/json

###  Categories delete
DELETE http://localhost:5000/product/7
Authorization: Bearer {{token}}

### Create Categories
POST http://localhost:5000/product/createCategories
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Electronics",
  "parentId": null,
  "isActive": true
}

### Update Categories
POST http://localhost:5000/product/updateCategories/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Electronics",
  "parentId": null,
  "isActive": false
}

### Fetch all categories
POST http://localhost:5000/product/getCategories
Content-Type: application/json

{
  "search": "",
  "page": 1,
  "limit": 10
}

### Create Product with Image
POST http://localhost:5000/product/createProduct
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="image.jpg"
Content-Type: image/jpeg

< ./db/testfile/image.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="dto"

{
  "businessId": 1,
  "categoryId": 2,
  "name": "Ultra Cement",
  "description": "High quality cement",
  "price": 450,
  "currency": "Rs",
  "minQuantity": 10
}
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Update Product by SKU
PATCH http://localhost:5000/product/updateProduct/CA15
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="image.jpg"
Content-Type: image/jpeg

< ./db/testfile/image.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="dto"

{
  "name": "Ultra Cement Premium",
  "price": 475,
  "description": "Updated description for better quality",
  "minQuantity": 20,
  "categoryId": 3
}
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###  Product delete
DELETE http://localhost:5000/product/deleteProduct/CA12
Authorization: Bearer {{token}}

###  Fetch all Product
POST http://localhost:5000/product/getProduct
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "search": "",
  "page":2,
  "sortBy": "price",
  "order": "ASC"
}