### baseURL
@baseURL = http://localhost:5000


### Get all users
GET {{baseURL}}/users

### Register a vendor
POST {{baseURL}}/auth/register
Content-Type: application/json

{
  "businessName": "TechSupplies Pvt Ltd",
  "businessEmail": "sales@techsupplies.com",
  "businessPhone": "9876543210",
  "businessAddress": "Bangalore, India",

  "email": "vendor1@example.com",
  "password": "password123",
  "name": "vendor name",
  "role": "vendor"
}


### Register a approver
POST {{baseURL}}/auth/register
Content-Type: application/json

{
  "businessName": "TechSupplies Pvt Ltd",

  "email": "approver@example.com",
  "password": "password123",
  "name": "approver name",
  "role": "approver"
}

### Register a buyer
POST {{baseURL}}/auth/register
Content-Type: application/json

{
  "phone": "9876543210",
  "designation": "Manager",
  "department": "IT",

  "email": "buyer@example.com",
  "password": "password123",
  "name": "buyer name",
  "role": "buyer",
}

### Register a admin
POST {{baseURL}}/auth/register
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "password123",
  "name": "admin name",
  "role": "admin",
  "phone": "9876543210"
}


### Login vendor
POST {{baseURL}}/auth/login
Content-Type: application/json

{
  "email": "vendor@example.com",
  "password": "password123"
}

### Login approver
POST {{baseURL}}/auth/login
Content-Type: application/json

{
  "email": "approver@example.com",
  "password": "password123"
}


### Login buyer
POST {{baseURL}}/auth/login
Content-Type: application/json

{
  "email": "buyer@example.com",
  "password": "password123"
}

### Login admin
POST {{baseURL}}/auth/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "password123"
}


### Manually set the access token here after login
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkMjU0MzgzMi01ZTY4LTQ5NTQtOTBmMi0wNjlhZTYzNjYxYzkiLCJpYXQiOjE3NjMyNDE5NDgsImV4cCI6MTc2MzI0Mjg0OH0.eYco5UwtAIC2vAv-G0QWoV-6RnReU4Z19WGAVcO8JZY

@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2N2M4NjhjMC03NWQ4LTQ1NTctOTE1MS1iNjcyZjhjNDUyNjkiLCJpYXQiOjE3NjMyMjMyMjgsImV4cCI6MTc2MzgyODAyOH0.m0wChIiB0Q6ilX-Nhuumj02eN0XvImlciUoD28tsl4s

### Refresh Token
POST {{baseURL}}/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}


### Fetch all categories
POST {{baseURL}}/categories/getCategories
Content-Type: application/json

{
  "search": "",
  "page": 1,
  "limit": 10
}

###  Categories delete
DELETE {{baseURL}}/categories/12
Authorization: Bearer {{token}}

### Create Categories
POST {{baseURL}}/categories/createCategories
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Construction2",
  "parentId": null,
  "isActive": true
}

### Update Categories
POST {{baseURL}}/categories/updateCategories/16
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Electronics9",
  "parentId": null,
  "isActive": false
}

###  Fetch all Product
POST {{baseURL}}/product/getProduct
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "search": "",
  "categoryId": null,
  "businessId" : null,
  "isActive":true,
  "page":1,
  "limit":10,
  "sortBy": "updatedAt", 
  "order": "DESC"
}
 # sortBy ='name', 'createdAt', 'updatedAt'

###  Fetch one Product
GET {{baseURL}}/product/getProductById/46
Authorization: Bearer {{token}}
Content-Type: application/json

### Create Product with Image
POST {{baseURL}}/product/createProduct
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="files"; filename="image.jpg"
Content-Type: image/jpeg

< ./db/testfile/image.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="files"; filename="image.jpg"
Content-Type: image/jpeg

< ./db/testfile/image.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="dto"

{
  "businessId": 1,
  "categoryId": 2,
  "name": "Ultra Cement",
  "description": "High quality cement",

  "isPriceAva": true,
  "price": 450,
  "currency": "INR",
  "minQuantity": 10
}
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Update Product by SKU
PATCH {{baseURL}}/product/updateProduct/1
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="files"; filename="image.jpg"
Content-Type: image/jpeg

< ./db/testfile/image.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="dto"

{
  "name": "Ultra Cement Premium",
  "description": "Updated description for better quality",
  "categoryId": 3
}
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###  Product delete
DELETE {{baseURL}}/product/deleteProduct/1
Authorization: Bearer {{token}}

### GET ALL Business Products (with pagination, filters, sorting)
POST {{baseURL}}/business-product/getAll
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "search": "",
  "page": 1,
  "limit": 10,
  "businessId": 2,
  "isActive": true,
  "sortBy": "price",
  "order": "ASC"
}

# sortBy = 'price', 'minQuantity', 'createdAt', 'updatedAt'

### GET Business Product by ID
GET {{baseURL}}/business-product/getById/12
Authorization: Bearer {{token}}

### Approval Group name
GET {{baseURL}}/approval-config/groups?search=&sort=DESC&page=1&limit=5
Content-Type: application/json
Authorization: Bearer {{token}}

### CREATE Business Product
POST {{baseURL}}/business-product/create
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "businessId": 2,
  "productId": 2,
  "price": 299.99,
  "currency": "INR",
  "minQuantity": 5,
  "groupName":"GROUP-1",
  "isActive": true
}

### UPDATE Business Product
PATCH {{baseURL}}/business-product/update/11
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "price": 249.99,
  "minQuantity": 3,
  "isActive": true
}

### DELETE Business Product
DELETE {{baseURL}}/business-product/delete/1
Authorization: Bearer {{token}}

### Get User Cart (with pagination)
POST {{baseURL}}/cart/getUserCart
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "page": 1,
  "limit": 10
}

### Add to Cart
POST {{baseURL}}/cart/addToCart
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "bpId": 1,
  "quantity": 1
}

### Remove Item from Cart
DELETE {{baseURL}}/cart/deleteFromCart/73
Content-Type: application/json
Authorization: Bearer {{token}}

### Update Item from Cart
POST {{baseURL}}/cart/addToCart
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "bpId": 12,
  "quantity": 1
}

### 1️⃣ Create Approval Config
POST {{baseURL}}/approval-config/create
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userId": 14,
  "approvalLevel": 1,
  "minAmount": 5000,
  "maxAmount": 10000,
  "autoApprove": false,
  "groupName" : "GROUP-1",
  "isActive": true
}


### Get All Approval Configs (Paginated)
POST {{baseURL}}/approval-config/find
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "page": 1,
  "limit": 10,
  "search": "",
  "groupName": "GROUP-1",
  "userId": null,
  "createdById": 16,
  "isActive": true,
  "sortBy": "createdAt",
  "sortOrder": "DESC"
}

# sortBy = 'approvalLevel','minAmount','maxAmount','createdAt','updatedAt',

### 3️⃣ Get Single Approval Config by ID
GET {{baseURL}}/approval-config/76
Authorization: Bearer {{token}}


### 4️⃣ Update Approval Config
PATCH {{baseURL}}/approval-config/76
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "approvalLevel": 2,
  "minAmount": 1000,
  "maxAmount": 10000,
  "autoApprove": false
}

### 5️⃣ Delete Approval Config
DELETE {{baseURL}}/approval-config/75
Authorization: Bearer {{token}}

### 5️⃣ Create Purchase Requests
GET {{baseURL}}/pr/create
Authorization: Bearer {{token}}

### Filter Purchase Requests (POST)
POST {{baseURL}}/pr/findAll
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "search": "PR-1763241252793",
  "requestedBy": null,
  "businessId": 1,
  "status": "APPROVED",
  "isActive": true,
  "page": 1,
  "limit": 20,
  "sortBy": "createdAt",
  "order": "DESC"
}

### 5️⃣ Create Purchase Requests
GET {{baseURL}}/pr/findOne/71
Authorization: Bearer {{token}}



