### baseURL
@baseURL = http://localhost:5000


### Get all users
GET {{baseURL}}/users

### Register a vendor
POST {{baseURL}}/auth/register
Content-Type: application/json

{
  "businessName": "TechSupplies Pvt Ltd",
  "businessEmail": "sales@techsupplies.com",
  "businessPhone": "9876543210",
  "businessAddress": "Bangalore, India",
  "phone": "9876543210",
  "designation": "Manager",
  "department": "IT",

  "email": "vendor@example.com",
  "password": "password123",
  "name": "vendor name",
  "role": "vendor"
}


### Register a approver
POST {{baseURL}}/auth/register
Content-Type: application/json

{
  "phone": "9876543210",
  "designation": "Manager",
  "department": "IT",

  "email": "approver@example.com",
  "password": "password123",
  "name": "approver name",
  "role": "approver"
}

### Register a buyer
POST {{baseURL}}/auth/register
Content-Type: application/json

{
  "email": "buyer@example.com",
  "password": "password123",
  "name": "buyer name",
  "role": "buyer",
  "phone": "9876543210"
}

### Register a admin
POST {{baseURL}}/auth/register
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "password123",
  "name": "admin name",
  "role": "admin",
  "phone": "9876543210"
}


### Login vendor
POST {{baseURL}}/auth/login
Content-Type: application/json

{
  "email": "vendor@example.com",
  "password": "password123"
}

### Login approver
POST {{baseURL}}/auth/login
Content-Type: application/json

{
  "email": "approver@example.com",
  "password": "password123"
}


### Login buyer
POST {{baseURL}}/auth/login
Content-Type: application/json

{
  "email": "buyer@example.com",
  "password": "password123"
}

### Login admin
POST {{baseURL}}/auth/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "password123"
}


### Manually set the access token here after login
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMTRmNjk0MC1iMDllLTQ4ZTgtYmVlOC1lZTYyNDRjOTM5YmUiLCJpYXQiOjE3NjIyNTU5NTAsImV4cCI6MTc2MjI1Njg1MH0.TmVeoTBqdgPwgYe1T7f3jGhIf6wsmYG4niFx5kqzWHA

@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyYzFmMGE4My1jMmIyLTRlNjEtOTI5Ni1kZTQ1NjE2OWQ1ODkiLCJpYXQiOjE3NjIxNDE3NTEsImV4cCI6MTc2Mjc0NjU1MX0.m8HKniFysuwk7vsZawyGeBQeolA7O7CMF6CW_3Jq-xc

### Refresh Token
POST {{baseURL}}/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

###  Fetch all categories with parent and children
GET {{baseURL}}/product/getAllCategories
Content-Type: application/json

###  Categories delete
DELETE {{baseURL}}/product/7
Authorization: Bearer {{token}}

### Create Categories
POST {{baseURL}}/product/createCategories
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Electronics",
  "parentId": null,
  "isActive": true
}

### Update Categories
POST {{baseURL}}/product/updateCategories/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Electronics",
  "parentId": null,
  "isActive": false
}

### Fetch all categories
POST {{baseURL}}/product/getCategories
Content-Type: application/json

{
  "search": "",
  "page": 1,
  "limit": 10
}

### Create Product with Image
POST {{baseURL}}/product/createProduct
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="files"; filename="image.jpg"
Content-Type: image/jpeg

< ./db/testfile/image.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="files"; filename="image.jpg"
Content-Type: image/jpeg

< ./db/testfile/image.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="dto"

{
  "businessId": 1,
  "categoryId": 2,
  "name": "Ultra Cement",
  "description": "High quality cement",
  "price": 450,
  "currency": "Rs",
  "minQuantity": 10,
  "isPriceAva": true
}
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Update Product by SKU
PATCH {{baseURL}}/product/updateProduct/SKU-1762227838030
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="files"; filename="image.jpg"
Content-Type: image/jpeg

< ./db/testfile/image.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="dto"

{
  "name": "Ultra Cement Premium",
  "description": "Updated description for better quality",
  "categoryId": 3
}
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###  Product delete
DELETE {{baseURL}}/product/deleteProduct/SKU-1762230292299
Authorization: Bearer {{token}}

###  Fetch all Product
POST {{baseURL}}/product/getProduct
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "search": "SKU-1762230292299",
  "page":1,
  "sortBy": "price",
  "order": "ASC"
}

### CREATE Business Product
POST {{baseURL}}/business-product/create
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "businessId": 1,
  "productId": 2,
  "price": 199.99,
  "currency": "USD",
  "minQuantity": 5,
  "isActive": true
}

### UPDATE Business Product
PATCH {{baseURL}}/business-product/update/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "price": 249.99,
  "minQuantity": 3,
  "isActive": true
}

### DELETE Business Product
DELETE {{baseURL}}/business-product/delete/1
Authorization: Bearer {{token}}

### GET Business Product by ID
GET {{baseURL}}/business-product/getById/1
Authorization: Bearer {{token}}

### GET ALL Business Products (with pagination, filters, sorting)
POST {{baseURL}}/business-product/getAll
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "search": "",
  "page": 1,
  "limit": 10,
  "businessId": 1,
  "isActive": true,
  "sortBy": "price",
  "order": "ASC"
}